### ISSUE TITLE
False controller connected messages

### ISSUE THREAD

**Issue by Simon818** [Technow-es/NVDARemoteServer#2]
Whenever I connect to my relay servers with any key at all, whether as a controller or a slave, NVDA beeps as though a controlling machine is connected. This can happen even when no controller is connected yet.

**Comment by jmdaweb** [comment]
In which platform are you running the server? It will have debugging options soon.


From: Simon818 
Sent: Wednesday, July 15, 2015 10:22 PM
To: Technow-es/NVDARemoteServer 
Subject: [NVDARemoteServer] False controller connected messages (#2)

Whenever I connect to my relay servers with any key at all, whether as a controller or a slave, NVDA beeps as though a controlling machine is connected. This can happen even when no controller is connected yet.

**Comment by Simon818** [comment]
I'm running it on Ubuntu 12 and 14.04 32 bit. Will try on Windows and see if this still happens, but I'm not sure why it would be any different.

**Comment by jmdaweb** [comment]
Hello.
I have added an option to debug the server. Run the following command:
NVDARemoteServer debug
You will see the server activity in the console, I hope that it help us to fix the isue. To stop the server, press ctrl+c.

**Comment by jmdaweb** [comment]
Hello.
I have partially fixed your problem. Previously, the client received information about all clients connected to the server, even if the key wasn't the same, so if 2 clients were connected with 2 diferent keys, the false positive appeared.
I am researching a lot about how to detect broken connections, but it is very difficult.

**Comment by Simon818** [comment]
I suspect it is difficult, but I wonder if there is some sort of keep 
alive system in place already. I feel like either NVDA or the server 
periodically pings the server to keep the connection alive, because I 
have seen it successfully abort broken connections on the NVDA side, and 
then keep retrying until the connection is re-established. I noticed the 
fact that all clients are reported as connected, and I think that was 
one of the main problems, so this will probably solve a lot of that. I 
haven't checked the git repository yet, but if the server is in fact 
fixed, i'll deploy it in a few places and see what happens.
