### ISSUE TITLE
Ubuntu: automatic server startup at system startup

### ISSUE THREAD

**Issue by beqabeqa473** [Technow-es/NVDARemoteServer#3]
hello.

i've installed nvdaremoteserver the latest codebase on ubuntu server14.04.

after system reboot, i need to run service manually, is it possible to start server at system startup?

**Comment by jmdaweb** [comment]
Hello.
Try running: service NVDARemoteServer enable
If it works, let me know so I can close the isue.


From: beqa gozalishvili 
Sent: Friday, July 17, 2015 8:31 PM
To: Technow-es/NVDARemoteServer 
Subject: [NVDARemoteServer] Ubuntu: automatic server startup at system startup (#3)

hello.

i've installed nvdaremoteserver the latest codebase on ubuntu server14.04.

after system reboot, i need to run service manually, is it possible to start server at system startup?

**Comment by beqabeqa473** [comment]
it seems you've forgotten to push something, there is no option to enable.

**Comment by jmdaweb** [comment]
Sorry, I sent you the wrong command. Try this one: update-rc.d –n NVDARemoteServer enable
Don’t forget to run this command from the root account or with sudo. Let me know if it works.

**Comment by beqabeqa473** [comment]
update-rc.d: warning:  start runlevel arguments (none) do not match NVDARemoteServer Default-Start values (2 3 4 5)
 System start/stop links for /etc/init.d/NVDARemoteServer do not exist.

**Comment by jmdaweb** [comment]
Ok. You should provide one or more run levels to update-rc.d. I don’t have any machine at this moment with the Ubuntu version that you are running, so I can’t give you the exact command. Try the following:
update-rc.d –n NVDARemoteServer enable 2
Or:
update-rc.d –n NVDARemoteServer enable 2 3 4 5
If you still get errors, read the manpage:
man update-rc.d

**Comment by beqabeqa473** [comment]
hi, even on debian8 i can't manage to start nvdaremote service at system startup.

**Comment by jmdaweb** [comment]
Finally I found the right command. It works on Ubuntu 15.04, and should work on Debian 8 too:
update-rc.d NVDARemoteServer enable
If it works, you shouldn’t see any output in the console, and NVDA Remote Server should start at system startup. I think that this command should work in debian 7 and older Ubuntu versions.
By default the service won’t run at system startup, the user will decide to enable it or not.

**Comment by beqabeqa473** [comment]
update-rc.d: error: no runlevel symlinks to modify, aborting!
r

i've built deb and just installed on clean server, nothing was done.

**Comment by jmdaweb** [comment]
I will make tests on debian 7 and debian 8 virtual machines.
