### ISSUE TITLE
Remove capital letters from systemd service and package names

### ISSUE THREAD

**Issue by leonardder** [Technow-es/NVDARemoteServer#4]
The use of capital letters in the systemd service name and package name slightly violates normal behavior of most distributions. I think lower case letters are better for consistency.

**Comment by jmdaweb** [comment]
I have tried that, but rpmlint and lintian package checkers throw warnings.

From: Leonard de Ruijter 
Sent: Tuesday, August 11, 2015 2:47 PM
To: Technow-es/NVDARemoteServer 
Subject: [NVDARemoteServer] Remove capital letters from systemd service and package names (#4)

The use of capital letters in the systemd service name and package name slightly violates normal behavior of most distributions. I think lower case letters are better for consistency.
